/vis/verbose 1
/vis/open OGL 600x600-0+0
/vis/ogl/set/displayListLimit 500000
/vis/multithreading/maxEventQueueSize 0

# Draw geometry:
/vis/drawVolume
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 24

# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/setRGBA gamma     0 1 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA proton    1 1 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e-        0 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA e+        0 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron   1 1 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA deuteron  1 0 1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA triton    0.1 0.2 0.1 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA alpha     1 0 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA ion       1 0 0 1

/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate 100000

# To draw only neutrons:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add neutron

# Decorations
/vis/set/textColour yellow
/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! Caption

# Axes
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo

/vis/geometry/set/visibility logicWorld 0 false
/vis/viewer/set/style wireframe
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 270 0

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/tracking/storeTrajectory 1
/vis/scene/add/scale
#/run/beamOn 1000000